-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 22:08:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tutorial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tutorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tutorial` DEFAULT CHARACTER SET big5 ;
USE `tutorial` ;

-- -----------------------------------------------------
-- Table `tutorial`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`country` (
  `id` INT NOT NULL,
  `sShortName` VARCHAR(2) NOT NULL,
  `sFullName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sShortName_UNIQUE` (`sShortName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorial`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`user` (
  `id` INT NOT NULL,
  `sFirstName` VARCHAR(45) NOT NULL,
  `sLastName` VARCHAR(45) NOT NULL,
  `nPassportID` INT NOT NULL,
  `sAddress` VARCHAR(45) NULL,
  `sCity` VARCHAR(45) NULL,
  `nCountryID` INT NULL,
  `nAge` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nPassportID_UNIQUE` (`nPassportID` ASC),
  INDEX `fk_users_countries1_idx` (`nCountryID` ASC),
  CONSTRAINT `fk_users_countries1`
    FOREIGN KEY (`nCountryID`)
    REFERENCES `tutorial`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorial`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`car` (
  `id` INT NOT NULL,
  `sBrand` VARCHAR(45) NOT NULL,
  `sModel` VARCHAR(45) NOT NULL,
  `nBuildYear` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tutorial`.`user_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`user_car` (
  `nUserID` INT NOT NULL,
  `nCarID` INT NOT NULL,
  PRIMARY KEY (`nUserID`, `nCarID`),
  INDEX `fk_users_has_cars_cars1_idx` (`nCarID` ASC),
  INDEX `fk_users_has_cars_users_idx` (`nUserID` ASC),
  CONSTRAINT `fk_users_has_cars_users`
    FOREIGN KEY (`nUserID`)
    REFERENCES `tutorial`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_cars_cars1`
    FOREIGN KEY (`nCarID`)
    REFERENCES `tutorial`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
